Repository Dudadakung/ReturnBottle-BE, pull requests merged in 2023-12, with the labels that each got.

#1 feat: 회원가입 및 CICD 구축
  .github/ISSUE_TEMPLATE/기능개발-issue-template.md
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  src/main/java/com/dudadakung/returnbottle/ReturnBottleApplication.java
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
  src/main/java/com/dudadakung/returnbottle/domain/BaseTimeEntity.java
  src/main/java/com/dudadakung/returnbottle/domain/Item.java
  src/main/java/com/dudadakung/returnbottle/domain/Reward.java
  src/main/java/com/dudadakung/returnbottle/domain/User.java
  src/main/java/com/dudadakung/returnbottle/domain/UserItem.java
  src/main/java/com/dudadakung/returnbottle/dto/User/request/UserLoginRequestDto.java
  src/main/java/com/dudadakung/returnbottle/dto/User/request/UserSignUpRequestDto.java
  src/main/java/com/dudadakung/returnbottle/dto/User/response/UserLoginResponseDto.java
  src/main/java/com/dudadakung/returnbottle/error/dto/ErrorBaseResponse.java
  src/main/java/com/dudadakung/returnbottle/error/exception/BusinessException.java
  src/main/java/com/dudadakung/returnbottle/error/exception/EntityNotFoundException.java
  src/main/java/com/dudadakung/returnbottle/error/exception/ErrorCode.java
  src/main/java/com/dudadakung/returnbottle/error/handler/GlobalExceptionHandler.java
  src/main/java/com/dudadakung/returnbottle/global/BaseApiResponse.java
  src/main/java/com/dudadakung/returnbottle/global/SuccessCode.java
  src/main/java/com/dudadakung/returnbottle/repository/ItemRepository.java
  src/main/java/com/dudadakung/returnbottle/repository/RewardRepository.java
  src/main/java/com/dudadakung/returnbottle/repository/UserItemRepository.java
  src/main/java/com/dudadakung/returnbottle/repository/UserRepository.java
  src/main/java/com/dudadakung/returnbottle/service/UserService.java
  src/main/resources/application.properties
Labels: FEAT 👻, SETTING 🧊, UPDATE 🥐

#2 fix: 도커파일 오타 수정
  Dockerfile
Labels: FIX 🔥

#3 setting: CORS 설정
  src/main/java/com/dudadakung/returnbottle/global/config/WebConfig.java
Labels: SETTING 🧊

#6 feat: myPage API 추가
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
  src/main/java/com/dudadakung/returnbottle/dto/User/response/MyPageResponseDto.java
  src/main/java/com/dudadakung/returnbottle/repository/UserRepository.java
  src/main/java/com/dudadakung/returnbottle/service/UserService.java
Labels: FEAT 👻

#7 feat: myPage API 추가
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
  src/main/java/com/dudadakung/returnbottle/dto/User/response/MyPageResponseDto.java
  src/main/java/com/dudadakung/returnbottle/repository/UserRepository.java
  src/main/java/com/dudadakung/returnbottle/service/UserService.java
Labels: FEAT 👻

#9 fix: myPage API 수정
  src/main/java/com/dudadakung/returnbottle/repository/UserRepository.java
  src/main/java/com/dudadakung/returnbottle/service/UserService.java
Labels: FIX 🔥

#10 Feat: 로그인 기능 추가
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
Labels: FEAT 👻

#13 feat: 상품 목록 API 개발
  src/main/java/com/dudadakung/returnbottle/controller/ItemController.java
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
  src/main/java/com/dudadakung/returnbottle/dto/Item/response/ItemResponse.java
  src/main/java/com/dudadakung/returnbottle/service/ItemService.java
Labels: FEAT 👻

#18 feat: 적립 내역 조회 API
  src/main/java/com/dudadakung/returnbottle/controller/RewardController.java
  src/main/java/com/dudadakung/returnbottle/domain/BaseTimeEntity.java
  src/main/java/com/dudadakung/returnbottle/domain/Reward.java
  src/main/java/com/dudadakung/returnbottle/dto/reward/response/RewardHistoryResponse.java
  src/main/java/com/dudadakung/returnbottle/service/RewardService.java
Labels: FEAT 👻

#27 Feat: 유저의 아이템 목록 불러오기 추가
  src/main/java/com/dudadakung/returnbottle/controller/UserController.java
  src/main/java/com/dudadakung/returnbottle/domain/UserItem.java
  src/main/java/com/dudadakung/returnbottle/dto/User/response/UserItemResponseDto.java
  src/main/java/com/dudadakung/returnbottle/repository/UserItemRepository.java
  src/main/java/com/dudadakung/returnbottle/service/UserService.java
Labels: FEAT 👻
